export const userConstants = {
  INIT_USER: 'INIT_AUTH',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SAFE_LOGOUT: 'SAFE_LOGOUT',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  RESET_USER: 'RESET_USER',
};

export const stateConstants = {
  STATE_DATA_REQUEST_STATUS: 'STATE_DATA_REQUEST_STATUS',
  STATE_LIST_FAILURE: 'STATE_LIST_FAILURE',
  RECEIVED_STATE_LIST: 'RECEIVED_STATE_LIST',
  STATE_SELECTED: 'STATE_SELECTED',
  STATE_ADD_SUCCESS: 'STATE_ADD_SUCCESS',
  STATE_ADD_FAILURE: 'STATE_ADD_FAILURE',
  STATE_UPDATE_SUCCESS: 'STATE_UPDATE_SUCCESS',
  STATE_UPDATE_FAILURE: 'STATE_UPDATE_FAILURE',
};

export const shopConstants = {
  PER_REQUISITE_SHOP_DATA: 'PER_REQUISITE_SHOP_DATA',
  SHOP_DATA_REQUEST_STATUS: 'SHOP_DATA_REQUEST_STATUS',
  SHOP_LIST_FAILURE: 'SHOP_LIST_FAILURE',
  RECEIVED_SHOP_LIST: 'GET_ALL_SHOP',
  SHOP_SELECTED: 'SHOP_SELECTED',
  SHOP_ADD_SUCCESS: 'SHOP_ADD_SUCCESS',
  SHOP_ADD_FAILURE: 'SHOP_ADD_FAILURE',
  SHOP_UPDATE_SUCCESS: 'SHOP_UPDATE_SUCCESS',
  SHOP_UPDATE_FAILURE: 'SHOP_UPDATE_FAILURE',
};

export const categoryConstants = {
  CATEGORY_DATA_REQUEST_STATUS: 'CATEGORY_DATA_REQUEST_STATUS',
  CATEGORY_LIST_FAILURE: 'CATEGORY_LIST_FAILURE',
  RECEIVED_CATEGORY_LIST: 'GET_ALL_CATEGORY',
  CATEGORY_SELECTED: 'CATEGORY_SELECTED',
  CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
  CATEGORY_ADD_FAILURE: 'CATEGORY_ADD_FAILURE',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  CATEGORY_UPDATE_FAILURE: 'CATEGORY_UPDATE_FAILURE',
};

export const attributeConstants = {
  ATTRIBUTE_DATA_REQUEST_STATUS: 'ATTRIBUTE_DATA_REQUEST_STATUS',
  ATTRIBUTE_LIST_FAILURE: 'ATTRIBUTE_LIST_FAILURE',
  RECEIVED_ATTRIBUTE_LIST: 'GET_ALL_ATTRIBUTE',
  ATTRIBUTE_SELECTED: 'ATTRIBUTE_SELECTED',
  ATTRIBUTE_ADD_SUCCESS: 'ATTRIBUTE_ADD_SUCCESS',
  ATTRIBUTE_ADD_FAILURE: 'ATTRIBUTE_ADD_FAILURE',
  ATTRIBUTE_UPDATE_SUCCESS: 'ATTRIBUTE_UPDATE_SUCCESS',
  ATTRIBUTE_UPDATE_FAILURE: 'ATTRIBUTE_UPDATE_FAILURE',
};

export const imageConstants = {
  IMAGE_DATA_REQUEST_STATUS: 'IMAGE_DATA_REQUEST_STATUS',
  IMAGE_LIST_FAILURE: 'IMAGE_LIST_FAILURE',
  RECEIVED_IMAGE_LIST: 'RECEIVED_IMAGE_LIST',
  IMAGE_SELECTED: 'IMAGE_SELECTED',
  IMAGE_ADD_SUCCESS: 'IMAGE_ADD_SUCCESS',
  IMAGE_ADD_FAILURE: 'IMAGE_ADD_FAILURE',
  IMAGE_UPDATE_SUCCESS: 'IMAGE_UPDATE_SUCCESS',
  IMAGE_UPDATE_FAILURE: 'IMAGE_UPDATE_FAILURE',
};

export const personConstants = {
  PERSON_DATA_REQUEST_STATUS: 'PERSON_DATA_REQUEST_STATUS',
  PERSON_LIST_FAILURE: 'PERSON_LIST_FAILURE',
  RECEIVED_PERSON_LIST: 'RECEIVED_PERSON_LIST',
  PERSON_SELECTED: 'PERSON_SELECTED',
  PERSON_ADD_SUCCESS: 'PERSON_ADD_SUCCESS',
  PERSON_ADD_FAILURE: 'PERSON_ADD_FAILURE',
  PERSON_UPDATE_SUCCESS: 'PERSON_UPDATE_SUCCESS',
  PERSON_UPDATE_FAILURE: 'PERSON_UPDATE_FAILURE',
};

export const productConstants = {
  PER_REQUISITE_PRODUCT_DATA: 'PER_REQUISITE_PRODUCT_DATA',
  PRODUCT_DATA_REQUEST_STATUS: 'PRODUCT_DATA_REQUEST_STATUS',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
  RECEIVED_PRODUCT_LIST: 'RECEIVED_PRODUCT_LIST',
  PRODUCT_SELECTED: 'PRODUCT_SELECTED',
  PRODUCT_SHOP: 'PRODUCT_SHOP',
  PRODUCT_ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
  PRODUCT_ADD_FAILURE: 'PRODUCT_ADD_FAILURE',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',
};

export const sourceProductConstants = {
  PER_REQUISITE_SOURCE_PRODUCT_DATA: 'PER_REQUISITE_SOURCE_PRODUCT_DATA',
  SOURCE_PRODUCT_DATA_REQUEST_STATUS: 'SOURCE_PRODUCT_DATA_REQUEST_STATUS',
  SOURCE_PRODUCT_LIST_FAILURE: 'SOURCE_PRODUCT_LIST_FAILURE',
  RECEIVED_SOURCE_PRODUCT_LIST: 'RECEIVED_SOURCE_PRODUCT_LIST',
  SOURCE_PRODUCT_SELECTED: 'SOURCE_PRODUCT_SELECTED',
  SOURCE_PRODUCT_SHOP: 'SOURCE_PRODUCT_SHOP',
  SOURCE_PRODUCT_ADD_SUCCESS: 'SOURCE_PRODUCT_ADD_SUCCESS',
  SOURCE_PRODUCT_ADD_FAILURE: 'SOURCE_PRODUCT_ADD_FAILURE',
  SOURCE_PRODUCT_UPDATE_SUCCESS: 'SOURCE_PRODUCT_UPDATE_SUCCESS',
  SOURCE_PRODUCT_UPDATE_FAILURE: 'SOURCE_PRODUCT_UPDATE_FAILURE',
};

export const productImageConstants = {
  PRODUCT_IMAGE_DATA_REQUEST_STATUS: 'PRODUCT_IMAGE_DATA_REQUEST_STATUS',
  PRODUCT_IMAGE_LIST_FAILURE: 'PRODUCT_IMAGE_LIST_FAILURE',
  RECEIVED_PRODUCT_IMAGE_LIST: 'RECEIVED_PRODUCT_IMAGE_LIST',
  PRODUCT_IMAGE_SELECTED: 'PRODUCT_IMAGE_SELECTED',
  PRODUCT_IMAGE_ADD_SUCCESS: 'PRODUCT_IMAGE_ADD_SUCCESS',
  PRODUCT_IMAGE_ADD_FAILURE: 'PRODUCT_IMAGE_ADD_FAILURE',
  PRODUCT_IMAGE_UPDATE_SUCCESS: 'PRODUCT_IMAGE_UPDATE_SUCCESS',
  PRODUCT_IMAGE_UPDATE_FAILURE: 'PRODUCT_IMAGE_UPDATE_FAILURE',
};

export const productSpecConstants = {
  PER_REQUISITE_PRODUCT_SPEC_DATA: 'PER_REQUISITE_PRODUCT_SPEC_DATA',
  PRODUCT_SPEC_DATA_REQUEST_STATUS: 'PRODUCT_SPEC_DATA_REQUEST_STATUS',
  PRODUCT_SPEC_LIST_FAILURE: 'PRODUCT_SPEC_LIST_FAILURE',
  RECEIVED_PRODUCT_SPEC_LIST: 'RECEIVED_PRODUCT_SPEC_LIST',
  PRODUCT_SPEC_SELECTED: 'PRODUCT_SPEC_SELECTED',
  PRODUCT_SPEC_ADD_SUCCESS: 'PRODUCT_SPEC_ADD_SUCCESS',
  PRODUCT_SPEC_ADD_FAILURE: 'PRODUCT_SPEC_ADD_FAILURE',
  PRODUCT_SPEC_UPDATE_SUCCESS: 'PRODUCT_SPEC_UPDATE_SUCCESS',
  PRODUCT_SPEC_UPDATE_FAILURE: 'PRODUCT_SPEC_UPDATE_FAILURE',
};

export const productCategoryConstants = {
  PER_REQUISITE_PRODUCT_CATEGORY_DATA: 'PER_REQUISITE_PRODUCT_CATEGORY_DATA',
  PRODUCT_CATEGORY_DATA_REQUEST_STATUS: 'PRODUCT_CATEGORY_DATA_REQUEST_STATUS',
  PRODUCT_CATEGORY_LIST_FAILURE: 'PRODUCT_CATEGORY_LIST_FAILURE',
  RECEIVED_PRODUCT_CATEGORY_LIST: 'RECEIVED_PRODUCT_CATEGORY_LIST',
  PRODUCT_CATEGORY_SELECTED: 'PRODUCT_CATEGORY_SELECTED',
  PRODUCT_CATEGORY_ADD_SUCCESS: 'PRODUCT_CATEGORY_ADD_SUCCESS',
  PRODUCT_CATEGORY_ADD_FAILURE: 'PRODUCT_CATEGORY_ADD_FAILURE',
  PRODUCT_CATEGORY_UPDATE_SUCCESS: 'PRODUCT_CATEGORY_UPDATE_SUCCESS',
  PRODUCT_CATEGORY_UPDATE_FAILURE: 'PRODUCT_CATEGORY_UPDATE_FAILURE',
};

export const unitConstants = {
  UNIT_DATA_REQUEST_STATUS: 'UNIT_DATA_REQUEST_STATUS',
  UNIT_LIST_FAILURE: 'UNIT_LIST_FAILURE',
  RECEIVED_UNIT_LIST: 'RECEIVED_UNIT_LIST',
  UNIT_SELECTED: 'UNIT_SELECTED',
  UNIT_ADD_SUCCESS: 'UNIT_ADD_SUCCESS',
  UNIT_ADD_FAILURE: 'UNIT_ADD_FAILURE',
  UNIT_UPDATE_SUCCESS: 'UNIT_UPDATE_SUCCESS',
  UNIT_UPDATE_FAILURE: 'UNIT_UPDATE_FAILURE',
};

export const brandConstants = {
  BRAND_DATA_REQUEST_STATUS: 'BRAND_DATA_REQUEST_STATUS',
  BRAND_LIST_FAILURE: 'BRAND_LIST_FAILURE',
  RECEIVED_BRAND_LIST: 'RECEIVED_BRAND_LIST',
  BRAND_SELECTED: 'BRAND_SELECTED',
  BRAND_ADD_SUCCESS: 'BRAND_ADD_SUCCESS',
  BRAND_ADD_FAILURE: 'BRAND_ADD_FAILURE',
  BRAND_UPDATE_SUCCESS: 'BRAND_UPDATE_SUCCESS',
  BRAND_UPDATE_FAILURE: 'BRAND_UPDATE_FAILURE',
};

